#!/bin/python3

import math
import os
import random
import re
import sys

# Complete the sockMerchant function below.
def sockMerchant(n, ar):
    _set = set(ar)
    count_dict = {k:ar.count(k) for k in _set}
    _sum = 0 
    for k,v in count_dict.items():
        if v>2:
            _sum+=v//2
    return _sum
        
            


if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    n = int(input())

    ar = list(map(int, input().rstrip().split()))

    result = sockMerchant(n, ar)

    fptr.write(str(result) + '\n')

    fptr.close()
